# Generated by Django 2.2 on 2020-08-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaranthings', '0002_auto_20200806_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(default='activity', max_length=40),
            preserve_default=False,
        ),
    ]
