# Generated by Django 2.2 on 2020-08-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaranthings', '0003_category_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
