# Generated by Django 2.2 on 2020-08-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quaranthings', '0004_auto_20200811_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='img_file',
        ),
    ]
