# Generated by Django 2.2 on 2020-08-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaranthings', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
